package tasks;

/**
 * @author 
 * Date					:
 * Test ScenarioID		:  
 * Test ScenarioName	:
 * Component			: 
 * Description			:
 * Update History		:
 */
public enum ActionEnum {
	TEXT_BOX,
	TEXT_BOX_NUM,
	BUTTON,
	MENU_ITEM,
	CLICK_CHECK_BOX,
	COMBO_BOX,
	CLEAR_TEXT,
	RADIO_BUTTON,
	LINK,
	RIGHT_CLICK,
	VERIFY_PAGE,
	IS_DISPLAYED,
	IS_DISABLED,
	IS_ENABLED,
	CLICK_ICON,
	CLICK_BACK,
	CLICK_LINK,
	CLICK_LINK_Xpath,
	LIST_BOX, 
	CLICK_BUTTON,
	TAB,
	ENTER,
	DOUBLE_CLICK, 
	CLICK, 
	CLOSE_WINDOW,
	EXPAND_GRID,
	MAXIMIZE_SCREEN,
	SET_PROPERTY,
	EXPAND_TREE, 
	INPUT_KEYS,
	CELL_CLICK,
	HOVER,
	RIGHT_CLICK_CR,
	HOVER_MENU_ITEM, 
	WAIT,
	VERIFY_TEXT,
	VERIFY_BUTTON,
	NAVIGATE_URL,
	VERIFY_DROP_DOWN,
    VERIFY_TEXT_BOX,
    SELECT_DROP_DOWN_VALUE,
    SELECT_CHECKBOX_BUTTON,
	VERIFY_TEXT_NOT_PRESENT,
	VERIFY_NO_ELEMENT_PRESENT,
	IS_POPUP_DISPLAYED,
	CLOSE_POPUP,
	ACCEPT_POPUP,
	IS_EXPANDED, 
	IS_COLLAPSED, 
	OPEN_NEW_TAB,
	VERIFY_URL,
	GET_TEXT,
    SET_SCREEN_SIZE,
    VERIFY_POSITION,
    SELECT_RADIO_BUTTON,CLOSE_NEW_TAB,
    SLEEP,
    MODAL,
	DOWNLOAD_DOC,
	Capturescreenprint,
	READ_FILE,
	Fill_Form,
	VERIFY_TEXT_FROM_LIST,
	VERIFY_Search_Products,
	scroll,
	DELETE_fromList,
	ActionON_Nth_Element,
	VERIFY_ELEMENT,
	Browser_Close,
	NavigateUrlnTab,
	ClosePopUp;
	


}


